config/routes.rb
FormObjectPresentation::Application.routes.draw do
  root to: 'orders#index'

  resources :orders, except: :show
end

app/models/edit_meme_form.rb
class EditMemeForm
  include Virtus.model
  extend ActiveModel::Naming
  include ActiveModel::Conversion
  include ActiveModel::Validations

  attribute :id, Integer
  attribute :name, String
  attribute :rating, Integer
  attribute :_destroy, Boolean, default: false

  validates :name, presence: true
  validates :rating,
            presence: true,
            inclusion: { in: 1..10, message: 'must be between 1 and 10' }
end

app/models/edit_order_form.rb
class EditOrderForm
  include Virtus.model
  extend ActiveModel::Naming
  include ActiveModel::Conversion
  include ActiveModel::Validations

  attribute :flavor_id, Integer
  attribute :serving_size_id, Integer
  attribute :scoops, Integer
  attribute :topping_ids, Array[Integer]
  attribute :memes, Array[EditMemeForm]

  attr_reader :model

  validates :flavor_id, :serving_size_id, presence: true
  validates :scoops, presence: true, inclusion: { in: [1, 2, 3] }
  validate :more_scoops_than_toppings
  validate :valid_memes?

  def initialize(model=nil, args={})
    @model = model
    super(build_initial_args(args))
    build_memes
  end

  # persists for Rails form helper
  def persisted?
    true
  end

  # delegate to model for Rails named routes
  def to_param
    model.to_param
  end

  def topping_ids=(toppings)
    filtered_toppings = toppings.reject { |t| !Topping.exists?(t) }
    super(filtered_toppings)
  end

  def save
    filter_memes!

    if valid?
      persist
      true
    else
      build_memes
      false
    end
  end

  private

  def build_memes
    (3 - memes.size).times { memes << Meme.new }
  end

  def build_initial_args(args)
    if args.empty?
      args = model.attributes
      args[:topping_ids] = model.topping_ids
    end
    args[:memes] ||= model.memes.map(&:attributes)
    args
  end

  def valid_memes?
    memes.each do |meme|
      unless meme.valid?
        meme.errors.each do |error, message|
          errors.add(error, message)
        end
      end
    end
  end

  def filter_memes!
    memes.delete_if { |meme| meme['name'].blank? && meme['rating'].blank? }
  end

  def more_scoops_than_toppings
    if scoops.to_i < topping_ids.delete_if { |x| x == '' }.size
      errors.add(:topping_ids, "can't be more than scoops")
    end
  end

  def persist
    @model = OrderUpdating.call(@model, attributes)
  end
end

app/models/flavor.rb
class Flavor < ActiveRecord::Base
  validates :name,
            presence: true,
            uniqueness: true
end

app/models/ice_cream.rb
class IceCream < ActiveRecord::Base
  belongs_to :flavor
  belongs_to :serving_size
  has_and_belongs_to_many :toppings
  has_many :memes, dependent: :destroy
end

app/models/ice_cream_price_updating.rb
class IceCreamPriceUpdating
  def self.call(ice_cream)
    new(ice_cream).call
  end

  def initialize(ice_cream)
    @ice_cream = ice_cream
  end

  def call
    meme_ratings = ice_cream.memes.reduce(0) { |sum, meme| sum += meme.rating }
    ice_cream.update_attributes!(price: ice_cream.price + meme_ratings)
    ice_cream
  end

  private

  attr_reader :ice_cream
end

app/models/meme.rb
class Meme < ActiveRecord::Base
  belongs_to :ice_cream

  def self.create_defaults(ice_cream)
    defaults.map do |name|
      ice_cream.memes.create!(name: name, rating: 8)
    end
  end

  def self.defaults
    ['Chocolate Rain', 'Much Delicious. Wow.']
  end
end

app/models/new_order_form.rb
class NewOrderForm
  include Virtus.model
  extend ActiveModel::Naming
  include ActiveModel::Conversion
  include ActiveModel::Validations

  attribute :flavor_id, Integer
  attribute :serving_size_id, Integer
  attribute :scoops, Integer
  attribute :topping_ids, Array[Integer]

  attr_reader :model

  validates :flavor_id, :serving_size_id, presence: true
  validates :scoops, presence: true, inclusion: { in: [1, 2, 3] }
  validate :more_scoops_than_toppings

  # does not persist for Rails form helper
  def persisted?
    false
  end

  # delegate to model for Rails named routes
  def to_param
    model.to_param
  end

  def topping_ids=(toppings)
    filtered_toppings = toppings.reject { |t| !Topping.exists?(t) }
    super(filtered_toppings)
  end

  def save
    if valid?
      persist
      true
    else
      false
    end
  end

  private

  def persist
    @model = OrderCreating.call(attributes)
  end

  def more_scoops_than_toppings
    if scoops.to_i < topping_ids.delete_if { |attr| attr == '' }.size
      errors.add(:topping_ids, "can't be more than scoops")
    end
  end
end

app/models/order_creating.rb
class OrderCreating
  def self.call(attributes={})
    new(attributes).call
  end

  def initialize(attributes)
    @flavor_id = attributes.fetch(:flavor_id)
    @serving_size_id = attributes.fetch(:serving_size_id)
    @topping_ids = attributes.fetch(:topping_ids)
    @scoops = attributes.fetch(:scoops)
  end

  def call
    IceCream.transaction do
      ice_cream = IceCream.create!(flavor_id: flavor_id,
                                   serving_size_id: serving_size_id,
                                   topping_ids: topping_ids,
                                   scoops: scoops,
                                   price: scoops * 100)

      Meme.create_defaults(ice_cream)
      IceCreamPriceUpdating.call(ice_cream)
      ice_cream
    end
  end

  private

  attr_reader :flavor_id,
              :serving_size_id,
              :topping_ids,
              :scoops
end

app/models/order_updating.rb
class OrderUpdating
  def self.call(ice_cream, attributes={})
    new(ice_cream, attributes).call
  end

  def initialize(ice_cream, attributes)
    @ice_cream = ice_cream
    @flavor_id = attributes.fetch(:flavor_id)
    @serving_size_id = attributes.fetch(:serving_size_id)
    @topping_ids = attributes.fetch(:topping_ids)
    @scoops = attributes.fetch(:scoops)
    @memes = attributes.fetch(:memes)
  end

  def call
    IceCream.transaction do
      ice_cream.update_attributes!(flavor_id: flavor_id,
                                   serving_size_id: serving_size_id,
                                   topping_ids: topping_ids,
                                   scoops: scoops,
                                   price: scoops * 100)

      memes.each do |meme|
        if meme._destroy
          Meme.destroy(meme.id)
        elsif meme.id
          Meme.find(meme.id).update_attributes!(updating_attributes(meme))
        else
          Meme.create!(updating_attributes(meme).merge(ice_cream: ice_cream))
        end
      end

      IceCreamPriceUpdating.call(ice_cream)
      ice_cream
    end
  end

  private

  attr_reader :ice_cream,
              :flavor_id,
              :serving_size_id,
              :topping_ids,
              :scoops,
              :memes

  def updating_attributes(meme)
    meme.attributes.keep_if { |attribute| [:name, :rating].include?(attribute) }
  end
end

app/models/serving_size.rb
class ServingSize < ActiveRecord::Base
  validates :name,
            presence: true,
            uniqueness: true
end

app/models/topping.rb
class Topping < ActiveRecord::Base
  has_and_belongs_to_many :ice_creams

  validates :name,
            presence: true,
            uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :find_ice_cream, only: [:edit, :update, :destroy]
  respond_to :html

  def index
    @orders = IceCream.order('created_at DESC')

    respond_with @orders
  end

  def new
    @order = NewOrderForm.new

    respond_with @order
  end

  def create
    @order = NewOrderForm.new(valid_params)

    if @order.save
      redirect_to edit_order_path(@order), notice: 'Your order was created.'
    else
      render :new
    end
  end

  def edit
    @order = EditOrderForm.new(@ice_cream)

    respond_with @order
  end

  def update
    @order = EditOrderForm.new(@ice_cream, valid_params)

    if @order.save
      redirect_to edit_order_path(@order), notice: 'Your order was updated.'
    else
      render :edit
    end
  end

  def destroy
    @ice_cream.destroy

    respond_with @ice_cream, notice: 'Your order was deleted.', location: orders_path
  end

  private

  def find_ice_cream
    @ice_cream = IceCream.find(params[:id])
  end

  def valid_params
    params
      .require(:order)
      .permit(:flavor_id,
              :serving_size_id,
              :scoops,
              topping_ids: [],
              memes: [:id, :name, :rating, :_destroy])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/ice_creams/_form.html.erb
<%= form_for ice_cream, html: { class: 'form-horizontal', role: 'form' } do |f| %>
  <% if ice_cream.errors.size > 0 %>
    <ul class="alert alert-danger">
      <% ice_cream.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  <% end %>

  <div class="form-group">
    <div class="col-sm-10">
      <%= f.label :flavor_id %>
      <%= f.select :flavor_id,
        Flavor.all.map { |flavor| [flavor.name.capitalize, flavor.id] }
      %>
    </div>
  </div>

  <div class="form-group">
    <div class="col-sm-10">
      <%= f.label :serving_size_id, 'Serving Size' %>
      <%= f.select :serving_size_id,
        ServingSize.all.map { |serving_size| [serving_size.name.capitalize, serving_size.id] }
      %>
    </div>
  </div>

  <div class="form-group">
    <div class="col-sm-10">
      <%= f.label :scoops %>
      <%= f.select :scoops, options_for_select(1..3, f.object.scoops) %>
    </div>
  </div>

  <fieldset>
    <legend>Toppings</legend>
    <div class="form-group">
      <div class="col-sm-10">
        <ul class="checkbox">
          <% Topping.all.each do |topping| %>
            <li>
              <%= label_tag "topping_ids_#{topping.name.parameterize.underscore}" do %>
                <%= topping.name.titleize %>
                <%= check_box_tag 'ice_cream[topping_ids][]',
                  topping.id,
                  ice_cream.toppings.include?(topping),
                  id: "topping_ids_#{topping.name.parameterize.underscore}" %>
              <% end %>
            </li>
            <%= hidden_field_tag 'ice_cream[topping_ids[]', '' %>
          <% end %>
        </ul>
      </div>
    </div>
  </fieldset>

  <% if ice_cream.persisted? %>
    <fieldset>
      <legend>Memes</legend>
      <div class="form-group">
        <%= f.fields_for :memes do |fields| %>
          <div class="col-sm-10">
            <%= fields.label :name %>
            <%= fields.text_field :name, html: { class: 'form-control' } %>

            <%= fields.label :rating %>
            <%= fields.select :rating, options_for_select(10.downto(1), fields.object.rating), include_blank: true %>

            <% if fields.object.persisted? %>
              <%= fields.label :_destroy, 'Delete' %>
              <%= fields.check_box :_destroy %>
            <% end %>
          </div>
        <% end %>
      </div>
    </fieldset>
  <% end %>

  <%= f.submit 'Make It So (Delicious)', class: 'btn btn-primary' %>
  <%= link_to 'Cancel', ice_creams_path, class: 'btn btn-primary' %>
<% end %>

app/views/ice_creams/edit.html.erb
<div class="row">
  <div class="col-md-8 col-md-offset-2">
    <h1>Update Your Order</h1>
    <h4><%= number_to_currency(@ice_cream.price / 100.0) %></h4>
    <hr />
    <%= render 'form', ice_cream: @ice_cream %>
  </div>
</div>

app/views/ice_creams/index.html.erb
<div class="row">
  <div class="col-md-8 col-md-offset-2">
    <h1>Your Orders</h1>

    <div>
      <%= link_to 'New Ice Cream Order', new_ice_cream_path %>
    </div>

    <% if @ice_creams.size > 0 %>
      <table class="table table-striped">
        <thead>
          <tr>
            <th>Order #</th>
            <th>Price</th>
            <th>Actions</th>
          </tr>
        </thead>

        <tbody>
          <% @ice_creams.each do |ice_cream| %>
            <tr>
              <td><%= link_to "Order ##{ice_cream.id}", edit_ice_cream_path(ice_cream) %></td>
              <td><%= number_to_currency(ice_cream.price / 100.0) %></td>
              <td><%= link_to 'Delete', ice_cream_path(ice_cream), method: :delete %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    <% end %>
  </div>
</div>

app/views/ice_creams/new.html.erb
<div class="row">
  <div class="col-md-8 col-md-offset-2">
    <h1>What Kind of Ice Cream Would You Like?</h1>
    <hr />
    <%= render 'form', ice_cream: @ice_cream %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Form Object Presentation</title>
  <%= stylesheet_link_tag 'application', media: 'all' %>
  <%= csrf_meta_tags %>
</head>
<body>

<% if flash %>
  <div class="row">
    <div class="col-md-8 col-md-offset-2">
      <% flash.each do |type, message| %>
        <div class="alert alert-<%= type %>"><%= message %></div>
      <% end %>
    </div>
  </div>
<% end %>

<%= yield %>

<%= javascript_include_tag 'application' %>

</body>
</html>

app/views/orders/_form.html.erb
<%= form_for order, as: :order, url: url, html: { class: 'form-horizontal', role: 'form' } do |f| %>
  <% if order.errors.size > 0 %>
    <ul class="alert alert-danger">
      <% order.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  <% end %>

  <div class="form-group">
    <div class="col-sm-10">
      <%= f.label :flavor_id %>
      <%= f.select :flavor_id,
        Flavor.all.map { |flavor| [flavor.name.capitalize, flavor.id] }
      %>
    </div>
  </div>

  <div class="form-group">
    <div class="col-sm-10">
      <%= f.label :serving_size_id, 'Serving Size' %>
      <%= f.select :serving_size_id,
        ServingSize.all.map { |serving_size| [serving_size.name.capitalize, serving_size.id] }
      %>
    </div>
  </div>

  <div class="form-group">
    <div class="col-sm-10">
      <%= f.label :scoops %>
      <%= f.select :scoops, options_for_select(1..3, f.object.scoops) %>
    </div>
  </div>

  <fieldset>
    <legend>Toppings</legend>
    <div class="form-group">
      <div class="col-sm-10">
        <ul class="checkbox">
          <% Topping.all.each do |topping| %>
            <li>
              <%= label_tag "topping_ids_#{topping.name.parameterize.underscore}" do %>
                <%= topping.name.titleize %>
                <%= check_box_tag 'order[topping_ids][]',
                  topping.id,
                  order.topping_ids.include?(topping.id),
                  id: "topping_ids_#{topping.name.parameterize.underscore}" %>
              <% end %>
            </li>
          <% end %>
        </ul>
      </div>
    </div>
  </fieldset>

  <% if order.persisted? %>
    <fieldset>
      <legend>Memes</legend>
      <div class="form-group">
        <% order.memes.each_with_index do |meme, index| %>
          <div class="col-sm-10">
            <% if meme.id %>
              <%= hidden_field_tag "order[memes][][id]", meme.id %>
            <% end %>

            <%= label_tag "order[memes][][name]", 'Name' %>
            <%= text_field_tag "order[memes][][name]", meme.name %>
            <%= label_tag "order[memes][][rating]", 'Rating' %>
            <%= select_tag "order[memes][][rating]", options_for_select(10.downto(1), meme.rating), include_blank: true %>

            <% if meme.id %>
              <%= label_tag "memes_destroy_#{index}" do %>
                <%= check_box_tag "order[memes][][_destroy]", 1, false, id: "memes_destroy_#{index}" %>
                Delete
              <% end %>
            <% end %>
          </div>
        <% end %>
      </div>
    </fieldset>
  <% end %>

  <%= f.submit 'Make It So (Delicious)', class: 'btn btn-primary' %>
  <%= link_to 'Cancel', orders_path, class: 'btn btn-primary' %>
<% end %>

app/views/orders/edit.html.erb
<div class="row">
  <div class="col-md-8 col-md-offset-2">
    <h1>Update Your Order</h1>
    <h4><%= number_to_currency(@ice_cream.price / 100.0) %></h4>
    <hr />
    <%= render 'form', order: @order, url: order_path(@order) %>
  </div>
</div>

app/views/orders/index.html.erb
<div class="row">
  <div class="col-md-8 col-md-offset-2">
    <h1>Your Orders</h1>

    <div>
      <%= link_to 'New Order', new_order_path %>
    </div>

    <% if @orders.size > 0 %>
      <table class="table table-striped">
        <thead>
          <tr>
            <th>Order #</th>
            <th>Price</th>
            <th>Actions</th>
          </tr>
        </thead>

        <tbody>
          <% @orders.each do |order| %>
            <tr>
              <td><%= link_to "Order ##{order.id}", edit_order_path(order) %></td>
              <td><%= number_to_currency(order.price / 100.0) %></td>
              <td><%= link_to 'Delete', order_path(order), method: :delete %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    <% end %>
  </div>
</div>

app/views/orders/new.html.erb
<div class="row">
  <div class="col-md-8 col-md-offset-2">
    <h1>What Kind of Ice Cream Would You Like?</h1>
    <hr />
    <%= render 'form', order: @order, url: orders_path %>
  </div>
</div>